/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#F7F4EE',
        'surface-dim': '#DCD9D9',
        'surface-bright': '#FCF9F8',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F6F3F2',
        'surface-container': '#F0EDED',
        'surface-container-high': '#EAE7E7',
        'surface-container-highest': '#ECE9E2',
        'on-surface': '#171717',
        'on-surface-variant': '#574142',
        'secondary': '#6B6B6B',
        'outline': '#8B7171',
        'outline-variant': '#DEBFBF',
        'soft-border': '#D9D5CC',
        'primary': '#6B0119',
        'primary-container': '#8B1E2D',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#FF9DA0',
        'tertiary': '#003A32',
        'tertiary-container': '#005348',
        'error': '#BA1A1A',
        'secondary-container': '#FD848C',
        'primary-fixed': '#FFDADA',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#F3F0EF',
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"Inter"', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'display-hero': ['"Playfair Display"', 'serif'],
        'headline-xl': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'headline-sm': ['"Playfair Display"', 'serif'],
        'body-lg': ['"Inter"', 'sans-serif'],
        'body-md': ['"Inter"', 'sans-serif'],
        'body-sm': ['"Inter"', 'sans-serif'],
        'label-md': ['"Inter"', 'sans-serif'],
        'label-sm': ['"Inter"', 'sans-serif'],
        'source-tag': ['"Inter"', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-xl-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'source-tag': ['11px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'margin': '2rem',
        'margin-mobile': '1rem',
        'gutter': '1.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2rem',
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      }
    },
  },
  plugins: [],
}
